name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY -b gh-pages dir
      - name: Setup commit
        run: | 
                cd dir
                pwd

      - name: Push 
        run: |
                pwd
                cd dir
                pwd




