name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
                git config --global user.name "gh-pages"
                git config --global user.name "gh-pages@example.com"
                mkdir dir
                git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY -b gh-pages dir
                date > date
                git add -A
                git commit -m updated
                git push origin gh-pages




